---
title: Forensics.im
author: Alexander Bilz
email: mail@forensics.im
description: Forensics.im is an Autopsy Plugin, which allows parsing levelDB of modern
  Electron-based Instant Messenger Applications like Microsoft Teams. Unlike the existing
  levelDB plugin, Forensics.im also parses the binary ldb files, which contain the
  majority of the entries and allows identifies individual entities, such as messages
  and contacts, and presents these in Autopsy's blackboard view.
baseurl: "/"
url: www.forensics.im
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
